# cluster.yaml
# A cluster with two managed nodegroups
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-demo
  region: us-east-1

managedNodeGroups:
  - name: eks-demo-cluster-managed-ng-1
    instanceType: t3.medium
    minSize: 1
    maxSize: 10
    desiredCapacity: 3